SET SQL DIALECT 3;

/* CREATE DATABASE 'd:\programas\ventas\base\ventas.gdb' PAGE_SIZE 4096

 DEFAULT CHARACTER SET  */

/* Table: AREASVENTA, Owner: SYSDBA */

CREATE TABLE "AREASVENTA" 
(
  "CLAVE"	SMALLINT NOT NULL,
  "NOMBRE"	CHAR(10) NOT NULL,
  "CAJA"	SMALLINT,
  "FECHA_UMOV"	TIMESTAMP NOT NULL,
 PRIMARY KEY ("CLAVE"),
 UNIQUE ("NOMBRE")
);

/* Table: ARTICULOS, Owner: SYSDBA */

CREATE TABLE "ARTICULOS" 
(
  "CLAVE"	INTEGER NOT NULL,
  "DESC_CORTA"	CHAR(20) NOT NULL,
  "DESC_LARGA"	CHAR(45) NOT NULL,
  "PRECIO1"	NUMERIC(15, 4) NOT NULL,
  "PRECIO2"	NUMERIC(15, 4) NOT NULL,
  "PRECIO3"	NUMERIC(15, 4) NOT NULL,
  "PRECIO4"	NUMERIC(15, 4) NOT NULL,
  "ULT_COSTO"	NUMERIC(15, 4),
  "COSTOPROM"	NUMERIC(15, 4),
  "DESC_AUTO"	CHAR(1) NOT NULL,
  "EXISTENCIA"	NUMERIC(15, 4),
  "MINIMO"	NUMERIC(15, 4),
  "MAXIMO"	NUMERIC(15, 4),
  "CATEGORIA"	SMALLINT DEFAULT NULL,
  "DEPARTAMENTO"	SMALLINT DEFAULT NULL,
  "TIPO"	SMALLINT,
  "PROVEEDOR1"	SMALLINT DEFAULT NULL,
  "PROVEEDOR2"	SMALLINT DEFAULT NULL,
  "IVA"	NUMERIC(8, 4) NOT NULL,
  "FECHA_CAP"	TIMESTAMP NOT NULL,
  "FECHA_UMOV"	TIMESTAMP,
  "ESTATUS"	CHAR(1),
  "ULTVENTA"	INTEGER,
  "ULTCOMPRA"	INTEGER,
  "UTILIDAD"    CHAR(300),
 PRIMARY KEY ("CLAVE")
);

/* Table: CAJAS, Owner: SYSDBA */

CREATE TABLE "CAJAS" 
(
  "NUMERO"	SMALLINT NOT NULL,
  "SERIETICKET"	CHAR(3),
  "SERIENOTA"	CHAR(3),
  "SERIEFACTURA"	CHAR(3),
  "NOMBRE"	CHAR(15) NOT NULL,
  "FECHA_UMOV"	TIMESTAMP NOT NULL,
 PRIMARY KEY ("NUMERO")
);

/* Table: CATEGORIAS, Owner: SYSDBA */

CREATE TABLE "CATEGORIAS" 
(
  "CLAVE"	SMALLINT NOT NULL,
  "NOMBRE"	CHAR(15) NOT NULL,
  "TIPO"	CHAR(1) NOT NULL,
  "FECHA_UMOV"	TIMESTAMP,
  "CUENTA"	CHAR(5) NOT NULL,
 PRIMARY KEY ("CLAVE")
);

/* Table: CLIENTES, Owner: SYSDBA */

CREATE TABLE "CLIENTES" 
(
  "CLAVE"	INTEGER NOT NULL,
  "NOMBRE"	CHAR(75) NOT NULL,
  "RFC"	CHAR(13),
  "CALLE"	CHAR(50),
  "COLONIA"	CHAR(30),
  "LOCALIDAD"	CHAR(25),
  "ESTADO"	CHAR(25),
  "CP"	CHAR(5),
  "ECORREO"	CHAR(50),
  "DESCUENTO"	NUMERIC(8, 4),
  "TELEFONO"	CHAR(20),
  "CREDENCIAL"	CHAR(13),
  "VENCIMCREDEN"	DATE,
  "LIMITECREDITO"	NUMERIC(15, 4),
  "ULTIMACOMPRA"	INTEGER,
  "CONTACTO"	CHAR(75),
  "EMPRESA"	CHAR(75),
  "RFCEMP"	CHAR(13),
  "CALLEEMP"	CHAR(35),
  "COLONIAEMP"	CHAR(30),
  "LOCALIDADEMP"	CHAR(25),
  "ESTADOEMP"	CHAR(25),
  "CPEMP"	CHAR(5),
  "CORREOEMP"	CHAR(50),
  "CELULAR"	CHAR(20),
  "FAXEMP"	CHAR(20),
  "TELEMP"	CHAR(20),
  "FECHACAP"	TIMESTAMP NOT NULL,
  "FECHAUMOV"	TIMESTAMP,
  "PRECIO"	SMALLINT,
  "CATEGORIA"	SMALLINT DEFAULT NULL,
  "ACUMULADO"	NUMERIC(15, 4) NOT NULL,
 UNIQUE ("NOMBRE"),
 PRIMARY KEY ("CLAVE")
);

/* Table: CODIGOS, Owner: SYSDBA */

CREATE TABLE "CODIGOS" 
(
  "ARTICULO"	INTEGER,
  "CODIGO"	CHAR(13) NOT NULL,
  "TIPO"	CHAR(1) NOT NULL,
 UNIQUE ("CODIGO")
);

/* Table: COMPRAS, Owner: SYSDBA */

CREATE TABLE "COMPRAS" 
(
  "CLAVE"	INTEGER NOT NULL,
  "CAJA"	SMALLINT NOT NULL,
  "PROVEEDOR"	SMALLINT DEFAULT NULL,
  "DOCUMENTO"	CHAR(13),
  "FECHA"	DATE NOT NULL,
  "IVA"	NUMERIC(15, 4) NOT NULL,
  "TOTAL"	NUMERIC(15, 4) NOT NULL,
  "USUARIO"	SMALLINT DEFAULT NULL,
  "ESTATUS"	CHAR(1) NOT NULL,
  "DESCUENTO"	NUMERIC(14, 4) NOT NULL,
  "FECHA_CAP"	DATE NOT NULL,
  "TIPO"	CHAR(1) NOT NULL,
 PRIMARY KEY ("CLAVE")
);

/* Table: COMPRASDET, Owner: SYSDBA */

CREATE TABLE "COMPRASDET" 
(
  "COMPRA"	INTEGER NOT NULL,
  "ORDEN"	SMALLINT NOT NULL,
  "ARTICULO"	INTEGER DEFAULT NULL,
  "CANTIDAD"	NUMERIC(15, 4) NOT NULL,
  "COSTO"	NUMERIC(15, 4) NOT NULL,
  "IVA"	NUMERIC(8, 4),
  "DESCUENTO"	NUMERIC(8, 4) NOT NULL
);

/* Table: COMPRASPAGO, Owner: SYSDBA */

CREATE TABLE "COMPRASPAGO" 
(
  "COMPRA"	INTEGER NOT NULL,
  "TIPOPAGO"	SMALLINT default null,
  "IMPORTE"	NUMERIC(15, 4) NOT NULL,
  "REFERENCIA"	CHAR(20)
);

/* Table: COMPROBANTES, Owner: SYSDBA */

CREATE TABLE "COMPROBANTES" 
(
  "VENTA"	INTEGER NOT NULL,
  "TIPO"	CHAR(1) NOT NULL,
  "NUMERO"	INTEGER NOT NULL,
  "CLIENTE"	INTEGER default null,
  "FECHA"	DATE NOT NULL,
  "ESTATUS"	CHAR(1) NOT NULL,
  "CAJA"	SMALLINT NOT NULL,
  "CLAVE"	INTEGER NOT NULL,
 PRIMARY KEY ("CLAVE")
);

/* Table: CONFIG, Owner: SYSDBA */

CREATE TABLE "CONFIG" 
(
  "MONEDAMENOR"	NUMERIC(8, 2),
  "LETRAENCODIGO"	CHAR(1),
  "PRECIO"	SMALLINT,
  "NOTAGLOBAL"	CHAR(1),
  "FACTURAGLOBAL"	CHAR(1),
  "TICKETGLOBAL"	CHAR(1),
  "COTIZACIONGLOBAL"	CHAR(1),
  "AJUSTEGLOBAL"	CHAR(1),
  "COMPROBANTEDEF"	CHAR(1),
  "PAGODEF"	SMALLINT default null,
  "DEVOLUCIONGLOBAL"	CHAR(1),
  "NOTACREDGLOBAL"	CHAR(1),
  "COMPROBANTECOMPRAS"	CHAR(1),
  "PAGOCOMPRAS"	CHAR(1)
);

/* Table: CONSECUTIVOS, Owner: SYSDBA */

CREATE TABLE "CONSECUTIVOS" 
(
  "COMPROBANTE"	CHAR(1) NOT NULL,
  "NUMERO"	INTEGER NOT NULL,
  "CAJA"	SMALLINT
);

/* Table: CORTES, Owner: SYSDBA */

CREATE TABLE "CORTES" 
(
  "FECHA"	DATE,
  "HORA"	TIME,
  "USUARIO"	SMALLINT default null,
  "CAJA"	SMALLINT NOT NULL
);

/* Table: DEPARTAMENTOS, Owner: SYSDBA */

CREATE TABLE "DEPARTAMENTOS" 
(
  "CLAVE"	SMALLINT NOT NULL,
  "NOMBRE"	CHAR(15) NOT NULL,
  "FECHA_UMOV"	TIMESTAMP,
 PRIMARY KEY ("CLAVE"),
 UNIQUE ("NOMBRE")
);

/* Table: DESCUENTOS, Owner: SYSDBA */

CREATE TABLE "DESCUENTOS" 
(
  "CLAVE"	INTEGER NOT NULL,
  "FECHAINI"	DATE NOT NULL,
  "FECHAFIN"	DATE NOT NULL,
  "ARTICULO"	INTEGER,
  "DEPARTAMENTO"	SMALLINT,
  "CATEGORIA"	SMALLINT,
  "TOTAL"	NUMERIC(15, 4),
  "CANTIDAD"	NUMERIC(15, 4),
  "PORCENTAJE"	NUMERIC(8, 4),
  "VOLUMEN"	NUMERIC(8, 4),
 PRIMARY KEY ("CLAVE")
);

/* Table: DESCUENTOSPAGO, Owner: SYSDBA */

CREATE TABLE "DESCUENTOSPAGO" 
(
  "TIPOPAGO"	SMALLINT
);

/* Table: EMPRESA, Owner: SYSDBA */

CREATE TABLE "EMPRESA" 
(
  "RFC"	CHAR(13),
  "NOMBRE"	CHAR(50) NOT NULL,
  "CALLE"	CHAR(35),
  "COLONIA"	CHAR(35),
  "LOCALIDAD"	CHAR(25),
  "ESTADO"	CHAR(20),
  "CP"	CHAR(5),
  "TELEFONO"	CHAR(20),
  "FAX"	CHAR(20),
  "CORREOE"	CHAR(50),
  "PAGINAWEB"	CHAR(50),
  "FECHA"	TIMESTAMP NOT NULL,
  "LOGO"	BLOB SUB_TYPE 0 SEGMENT SIZE 80
);

/* Table: INVENTARIO, Owner: SYSDBA */

CREATE TABLE "INVENTARIO" 
(
  "CLAVE"	SMALLINT NOT NULL,
  "FECHA"	DATE NOT NULL,
  "APLICADO"	CHAR(1) NOT NULL,
  "DESCRIP"	CHAR(30) NOT NULL,
 PRIMARY KEY ("CLAVE")
);

/* Table: INVENTDET, Owner: SYSDBA */

CREATE TABLE "INVENTDET" 
(
  "INVENTARIO"	SMALLINT NOT NULL,
  "ARTICULO"	INTEGER NOT NULL,
  "CANTIDAD"	NUMERIC(15, 4),
  "EXISTENCIA"	NUMERIC(15, 4),
  "CANTJUEGO"	NUMERIC(15, 4),
  "JUEGO"	CHAR(1)
);

/* Table: JUEGOS, Owner: SYSDBA */

CREATE TABLE "JUEGOS" 
(
  "CLAVE"	INTEGER NOT NULL,
  "ARTICULO"	INTEGER NOT NULL,
  "CANTIDAD"	NUMERIC(15, 4) NOT NULL,
  "PRECIO"	NUMERIC(15, 4)
);

/* Table: NOTASCREDITO, Owner: SYSDBA */

CREATE TABLE "NOTASCREDITO" 
(
  "NUMERO"	INTEGER NOT NULL,
  "FECHA"	DATE NOT NULL,
  "CLIENTE"	INTEGER NOT NULL,
  "IMPORTE"	NUMERIC(15, 4) NOT NULL,
  "ESTATUS"	CHAR(1) NOT NULL,
  "CLAVE"	INTEGER NOT NULL,
  "CAJA"	SMALLINT NOT NULL,
  "COMPROBANTE"	INTEGER NOT NULL,
 PRIMARY KEY ("CLAVE")
);

/* Table: PERMISOS, Owner: SYSDBA */

CREATE TABLE "PERMISOS" 
(
  "USUARIO"	SMALLINT,
  "MENU"	SMALLINT NOT NULL,
  "OPCIONES"	SMALLINT NOT NULL,
  "PERMISO"	SMALLINT NOT NULL
);

/* Table: PRIVILEGIOS, Owner: SYSDBA */

CREATE TABLE "PRIVILEGIOS" 
(
  "USUARIO"	SMALLINT NOT NULL,
  "CLAVE"	CHAR(3) NOT NULL,
  "ADICIONAL"	CHAR(15)
);

/* Table: PROVEEDORES, Owner: SYSDBA */

CREATE TABLE "PROVEEDORES" 
(
  "CLAVE"	SMALLINT NOT NULL,
  "RFC"	CHAR(13),
  "NOMBRE"	CHAR(50) NOT NULL,
  "CALLE"	CHAR(35),
  "COLONIA"	CHAR(25),
  "CP"	CHAR(5),
  "LOCALIDAD"	CHAR(25),
  "ESTADO"	CHAR(25),
  "ENCARGADO"	CHAR(50),
  "FAX"	CHAR(15),
  "ECORREO"	CHAR(50),
  "FECHA_CAP"	TIMESTAMP NOT NULL,
  "TELEFONO"	CHAR(20),
  "FECHA_UMOV"	TIMESTAMP,
  "CATEGORIA"	SMALLINT DEFAULT NULL,
  "ULTCOMPRA"	INTEGER,
  "NOMBREFISCAL"	CHAR(50),
 PRIMARY KEY ("CLAVE")
);

/* Table: RETIROS, Owner: SYSDBA */

CREATE TABLE "RETIROS" 
(
  "FECHA"	DATE NOT NULL,
  "HORA"	TIME NOT NULL,
  "USUARIO"	INTEGER NOT NULL,
  "IMPORTE"	NUMERIC(15, 4),
  "CAJA"	SMALLINT
);

/* Table: TICKET, Owner: SYSDBA */

CREATE TABLE "TICKET" 
(
  "NIVEL"	SMALLINT NOT NULL,
  "RENGLON"	SMALLINT NOT NULL,
  "TEXTO"	VARCHAR(40) NOT NULL,
 PRIMARY KEY ("NIVEL", "RENGLON")
);

/* Table: TIPOPAGO, Owner: SYSDBA */

CREATE TABLE "TIPOPAGO" 
(
  "CLAVE"	SMALLINT NOT NULL,
  "NOMBRE"	CHAR(20) NOT NULL,
  "ABRIRCAJON"	CHAR(1) NOT NULL,
  "REFERENCIA"	CHAR(1),
  "FECHA_UMOV"	TIMESTAMP NOT NULL,
  "PAGOS"	SMALLINT,
  "PLAZO"	SMALLINT,
  "INTERES"	NUMERIC(8, 2),
  "ENGANCHE"	NUMERIC(8, 2),
  "MONTOMINIMO"	NUMERIC(15, 4),
  "APLICA"	CHAR(4),
  "INTMORATORIO"	NUMERIC(8, 2),
  "TIPOINTERES"	CHAR(1),
  "TIPOPLAZO"	SMALLINT,
  "MODO"	CHAR(20) NOT NULL,
 PRIMARY KEY ("CLAVE")
);

/* Table: USUARIOS, Owner: SYSDBA */

CREATE TABLE "USUARIOS" 
(
  "CLAVE"	INTEGER NOT NULL,
  "LOGIN"	CHAR(10) NOT NULL,
  "CONTRA"	CHAR(20) NOT NULL,
  "NOMBRE"	CHAR(50) NOT NULL,
  "CALLE"	CHAR(35),
  "COLONIA"	CHAR(25),
  "CP"	CHAR(5),
  "LOCALIDAD"	CHAR(25),
  "ESTADO"	CHAR(25),
  "TELEFONO"	CHAR(20),
  "FECHA_CAP"	TIMESTAMP,
  "FECHA_UMOV"	TIMESTAMP,
  "DESCUENTO"	NUMERIC(8, 4) NOT NULL,
 UNIQUE ("LOGIN"),
 PRIMARY KEY ("CLAVE")
);

/* Table: VENDEDORES, Owner: SYSDBA */

CREATE TABLE "VENDEDORES" 
(
  "CLAVE"	SMALLINT NOT NULL,
  "RFC"	CHAR(13),
  "NOMBRE"	CHAR(50) NOT NULL,
  "CALLE"	CHAR(35),
  "COLONIA"	CHAR(25),
  "CP"	CHAR(5),
  "LOCALIDAD"	CHAR(25),
  "ESTADO"	CHAR(25),
  "FAX"	CHAR(15),
  "ECORREO"	CHAR(50),
  "FECHA_CAP"	TIMESTAMP NOT NULL,
  "TELEFONO"	CHAR(20),
  "FECHA_UMOV"	TIMESTAMP,
  "CATEGORIA"	SMALLINT DEFAULT NULL,
  "ULTVENTA"	INTEGER,
 PRIMARY KEY ("CLAVE")
);

/* Table: VENTAS, Owner: SYSDBA */

CREATE TABLE "VENTAS" 
(
  "CLAVE"	INTEGER NOT NULL,
  "CAJA"	SMALLINT NOT NULL,
  "NUMERO"	INTEGER NOT NULL,
  "IVA"	NUMERIC(15, 4),
  "TOTAL"	NUMERIC(15, 4) NOT NULL,
  "CAMBIO"	NUMERIC(15, 4) NOT NULL,
  "REDONDEO"	NUMERIC(8, 2) NOT NULL,
  "ESTATUS"	CHAR(1) NOT NULL,
  "CLIENTE"	INTEGER default null,
  "USUARIO"	SMALLINT default null,
  "FECHA"	DATE NOT NULL,
  "HORA"	TIME NOT NULL,
  "AREAVENTA"	SMALLINT default null,
  "VENDEDOR"	SMALLINT default null,
  "VENTAREF"	INTEGER,
 PRIMARY KEY ("CLAVE")
);

/* Table: VENTASAREAS, Owner: SYSDBA */

CREATE TABLE "VENTASAREAS" 
(
  "AREAVENTA"	SMALLINT NOT NULL,
  "ORDEN"	SMALLINT,
  "ARTICULO"	INTEGER,
  "CODIGO"	CHAR(13) NOT NULL,
  "DESCRIP"	CHAR(20) NOT NULL,
  "CANTIDAD"	NUMERIC(15, 4) NOT NULL,
  "PRECIO"	NUMERIC(15, 4) NOT NULL,
  "IVA"	NUMERIC(15, 4) NOT NULL,
  "TIPO"	SMALLINT NOT NULL,
  "DESCAUTO"	CHAR(1) NOT NULL,
  "DESCOTORG"	NUMERIC(15, 4) NOT NULL,
  "DESCFECHAS"	NUMERIC(15, 4) NOT NULL,
  "CLIENTE"	INTEGER default null,
  "COMPROBANTE"	CHAR(1) NOT NULL,
  "CATEGORIA"	SMALLINT NOT NULL,
  "DEPARTAMENTO"	SMALLINT NOT NULL,
  "VENTAREF"	INTEGER,
  "VENTAREFORDEN"	SMALLINT
);

/* Table: VENTASDET, Owner: SYSDBA */

CREATE TABLE "VENTASDET" 
(
  "VENTA"	INTEGER NOT NULL,
  "ARTICULO"	INTEGER DEFAULT NULL,
  "CANTIDAD"	NUMERIC(15, 4) NOT NULL,
  "IVA"	NUMERIC(5, 2) NOT NULL,
  "PRECIO"	NUMERIC(15, 4) NOT NULL,
  "DESCUENTO"	NUMERIC(8, 2) NOT NULL,
  "ORDEN"	SMALLINT NOT NULL,
  "JUEGO"	SMALLINT NOT NULL,
  "DEVOLUCION"	NUMERIC(12, 4) NOT NULL,
  "VENTAREFORDEN"	SMALLINT,
 PRIMARY KEY ("VENTA", "ORDEN", "JUEGO")
);

/* Table: VENTASPAGO, Owner: SYSDBA */

CREATE TABLE "VENTASPAGO" 
(
  "VENTA"	INTEGER NOT NULL,
  "TIPOPAGO"	SMALLINT default null,
  "IMPORTE"	NUMERIC(15, 4) NOT NULL,
  "REFERENCIA"	CHAR(20),
  "ORDEN"	SMALLINT NOT NULL,
  "NOTACREDITO"	INTEGER default null
);

/* Table: XCOBRAR, Owner: SYSDBA */

CREATE TABLE "XCOBRAR" 
(
  "CLAVE"	INTEGER NOT NULL,
  "VENTA"	INTEGER NOT NULL,
  "IMPORTE"	NUMERIC(15, 4) NOT NULL,
  "PLAZO"	SMALLINT NOT NULL,
  "INTERES"	NUMERIC(8, 4) NOT NULL,
  "INTMORATORIO"	NUMERIC(8, 4) NOT NULL,
  "PROXIMOPAGO"	DATE NOT NULL,
  "TIPOINTERES"	CHAR(1) NOT NULL,
  "TIPOPLAZO"	SMALLINT NOT NULL,
  "ESTATUS"	CHAR(1) NOT NULL,
  "CLIENTE"	INTEGER NOT NULL,
  "FECHA"	DATE NOT NULL,
  "NUMPAGO"	CHAR(7) NOT NULL,
  "CANTINTMORAT"	NUMERIC(15, 4) NOT NULL,
  "CANTINTERES"	NUMERIC(15, 4) NOT NULL,
  "PAGADO"	NUMERIC(15, 4) NOT NULL,
  "ORDEN"	SMALLINT NOT NULL,
 PRIMARY KEY ("CLAVE")
);

/* Table: XCOBRARPAGOS, Owner: SYSDBA */

CREATE TABLE "XCOBRARPAGOS" 
(
  "XCOBRAR"	INTEGER NOT NULL,
  "NUMERO"	SMALLINT NOT NULL,
  "FECHA"	DATE NOT NULL,
  "IMPORTE"	NUMERIC(15, 4) NOT NULL,
  "INTERES"	NUMERIC(15, 4) NOT NULL,
  "INTERESMORAT"	NUMERIC(15, 4) NOT NULL,
  "TIPOPAGO"	SMALLINT default null,
  "COMENTARIO"	CHAR(30) NOT NULL,
 PRIMARY KEY ("XCOBRAR", "NUMERO")
);

/* Table: XPAGAR, Owner: SYSDBA */

CREATE TABLE "XPAGAR" 
(
  "CLAVE"	INTEGER NOT NULL,
  "COMPRA"	INTEGER NOT NULL,
  "IMPORTE"	NUMERIC(15, 4) NOT NULL,
  "PLAZO"	SMALLINT NOT NULL,
  "INTERES"	NUMERIC(8, 4) NOT NULL,
  "INTMORATORIO"	NUMERIC(8, 4) NOT NULL,
  "PROXIMOPAGO"	DATE NOT NULL,
  "TIPOINTERES"	CHAR(1) NOT NULL,
  "TIPOPLAZO"	SMALLINT NOT NULL,
  "ESTATUS"	CHAR(1) NOT NULL,
  "PROVEEDOR"	INTEGER NOT NULL,
  "FECHA"	DATE NOT NULL,
  "NUMPAGO"	CHAR(7) NOT NULL,
  "CANTINTMORAT"	NUMERIC(15, 4) NOT NULL,
  "CANTINTERES"	NUMERIC(15, 4) NOT NULL,
  "PAGADO"	NUMERIC(15, 4) NOT NULL,
 PRIMARY KEY ("CLAVE")
);

/* Table: XPAGARPAGOS, Owner: SYSDBA */

CREATE TABLE "XPAGARPAGOS" 
(
  "XPAGAR"	INTEGER NOT NULL,
  "NUMERO"	SMALLINT NOT NULL,
  "FECHA"	DATE NOT NULL,
  "IMPORTE"	NUMERIC(15, 4) NOT NULL,
  "INTERES"	NUMERIC(15, 4) NOT NULL,
  "INTERESMORAT"	NUMERIC(15, 4) NOT NULL,
  "TIPOPAGO"	SMALLINT default null,
  "COMENTARIO"	CHAR(30) NOT NULL,
 PRIMARY KEY ("XPAGAR", "NUMERO")
);

/*  Index definitions for all user tables */

CREATE INDEX "DESC_CORTA" ON "ARTICULOS"("DESC_CORTA");
CREATE INDEX "DESC_LARGA" ON "ARTICULOS"("DESC_LARGA");
CREATE INDEX "TIPOARTICULO" ON "ARTICULOS"("TIPO");
CREATE INDEX "CATEGNOMBRE" ON "CATEGORIAS"("NOMBRE");
CREATE INDEX "CATEGTIPO" ON "CATEGORIAS"("TIPO");
CREATE INDEX "CLIENTES_CRED" ON "CLIENTES"("CREDENCIAL");
CREATE INDEX "CLIENTES_RFC" ON "CLIENTES"("RFC");
CREATE INDEX "DEPTOS_NOM" ON "DEPARTAMENTOS"("NOMBRE");
CREATE INDEX "DESC_FIN" ON "DESCUENTOS"("FECHAFIN");
CREATE INDEX "DESC_INI" ON "DESCUENTOS"("FECHAINI");
CREATE INDEX "PROV_RFC" ON "PROVEEDORES"("RFC");
CREATE INDEX "VENTAS_FECHA" ON "VENTAS"("FECHA");
CREATE INDEX "VENTAS_NUMERO" ON "VENTAS"("CAJA", "NUMERO");
ALTER TABLE "ARTICULOS" ADD FOREIGN KEY ("DEPARTAMENTO") REFERENCES "DEPARTAMENTOS" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "ARTICULOS" ADD FOREIGN KEY ("CATEGORIA") REFERENCES "CATEGORIAS" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "ARTICULOS" ADD FOREIGN KEY ("PROVEEDOR1") REFERENCES "PROVEEDORES" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "ARTICULOS" ADD FOREIGN KEY ("PROVEEDOR2") REFERENCES "PROVEEDORES" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "CLIENTES" ADD FOREIGN KEY ("CATEGORIA") REFERENCES "CATEGORIAS" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "CODIGOS" ADD FOREIGN KEY ("ARTICULO") REFERENCES "ARTICULOS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "COMPRAS" ADD FOREIGN KEY ("PROVEEDOR") REFERENCES "PROVEEDORES" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "COMPRAS" ADD FOREIGN KEY ("USUARIO") REFERENCES "USUARIOS" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "COMPRASDET" ADD FOREIGN KEY ("COMPRA") REFERENCES "COMPRAS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "COMPRASDET" ADD FOREIGN KEY ("ARTICULO") REFERENCES "ARTICULOS" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "COMPRASPAGO" ADD FOREIGN KEY ("COMPRA") REFERENCES "COMPRAS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "COMPRASPAGO" ADD FOREIGN KEY ("TIPOPAGO") REFERENCES "TIPOPAGO" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "COMPROBANTES" ADD FOREIGN KEY ("VENTA") REFERENCES "VENTAS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "COMPROBANTES" ADD FOREIGN KEY ("CLIENTE") REFERENCES "CLIENTES" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "CONFIG" ADD FOREIGN KEY ("PAGODEF") REFERENCES "TIPOPAGO" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "CORTES" ADD FOREIGN KEY ("USUARIO") REFERENCES "USUARIOS" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "DESCUENTOS" ADD FOREIGN KEY ("DEPARTAMENTO") REFERENCES "DEPARTAMENTOS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "DESCUENTOS" ADD FOREIGN KEY ("CATEGORIA") REFERENCES "CATEGORIAS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "DESCUENTOS" ADD FOREIGN KEY ("ARTICULO") REFERENCES "ARTICULOS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "DESCUENTOSPAGO" ADD FOREIGN KEY ("TIPOPAGO") REFERENCES "TIPOPAGO" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "INVENTDET" ADD FOREIGN KEY ("INVENTARIO") REFERENCES "INVENTARIO" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "INVENTDET" ADD FOREIGN KEY ("ARTICULO") REFERENCES "ARTICULOS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "JUEGOS" ADD FOREIGN KEY ("CLAVE") REFERENCES "ARTICULOS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "JUEGOS" ADD FOREIGN KEY ("ARTICULO") REFERENCES "ARTICULOS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "NOTASCREDITO" ADD FOREIGN KEY ("CLIENTE") REFERENCES "CLIENTES" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "NOTASCREDITO" ADD FOREIGN KEY ("COMPROBANTE") REFERENCES "COMPROBANTES" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "PERMISOS" ADD FOREIGN KEY ("USUARIO") REFERENCES "USUARIOS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "PRIVILEGIOS" ADD FOREIGN KEY ("USUARIO") REFERENCES "USUARIOS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "PROVEEDORES" ADD FOREIGN KEY ("CATEGORIA") REFERENCES "CATEGORIAS" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "RETIROS" ADD FOREIGN KEY ("USUARIO") REFERENCES "USUARIOS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "VENDEDORES" ADD FOREIGN KEY ("CATEGORIA") REFERENCES "CATEGORIAS" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "VENTAS" ADD FOREIGN KEY ("AREAVENTA") REFERENCES "AREASVENTA" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "VENTAS" ADD FOREIGN KEY ("CLIENTE") REFERENCES "CLIENTES" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "VENTAS" ADD FOREIGN KEY ("USUARIO") REFERENCES "USUARIOS" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "VENTAS" ADD FOREIGN KEY ("VENDEDOR") REFERENCES "VENDEDORES" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "VENTAS" ADD FOREIGN KEY ("VENTAREF") REFERENCES "VENTAS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "VENTASAREAS" ADD FOREIGN KEY ("AREAVENTA") REFERENCES "AREASVENTA" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "VENTASAREAS" ADD FOREIGN KEY ("ARTICULO") REFERENCES "ARTICULOS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "VENTASAREAS" ADD FOREIGN KEY ("CLIENTE") REFERENCES "CLIENTES" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "VENTASAREAS" ADD FOREIGN KEY ("VENTAREF") REFERENCES "VENTAS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "VENTASDET" ADD FOREIGN KEY ("VENTA") REFERENCES "VENTAS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "VENTASDET" ADD FOREIGN KEY ("ARTICULO") REFERENCES "ARTICULOS" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "VENTASPAGO" ADD FOREIGN KEY ("VENTA") REFERENCES "VENTAS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "VENTASPAGO" ADD FOREIGN KEY ("TIPOPAGO") REFERENCES "TIPOPAGO" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "VENTASPAGO" ADD FOREIGN KEY ("NOTACREDITO") REFERENCES "NOTASCREDITO" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "XCOBRAR" ADD FOREIGN KEY ("VENTA") REFERENCES "VENTAS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "XCOBRAR" ADD FOREIGN KEY ("CLIENTE") REFERENCES "CLIENTES" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "XCOBRARPAGOS" ADD FOREIGN KEY ("TIPOPAGO") REFERENCES "TIPOPAGO" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "XCOBRARPAGOS" ADD FOREIGN KEY ("XCOBRAR") REFERENCES "XCOBRAR" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "XPAGAR" ADD FOREIGN KEY ("COMPRA") REFERENCES "COMPRAS" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "XPAGAR" ADD FOREIGN KEY ("PROVEEDOR") REFERENCES "PROVEEDORES" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "XPAGARPAGOS" ADD FOREIGN KEY ("TIPOPAGO") REFERENCES "TIPOPAGO" ("CLAVE") ON UPDATE CASCADE ON DELETE SET DEFAULT;
ALTER TABLE "XPAGARPAGOS" ADD FOREIGN KEY ("XPAGAR") REFERENCES "XPAGAR" ("CLAVE") ON UPDATE CASCADE ON DELETE CASCADE;

CREATE GENERATOR "AREASVENTA";
CREATE GENERATOR "ARTICULOS";
CREATE GENERATOR "CATEGORIAS";
CREATE GENERATOR "CLIENTES";
CREATE GENERATOR "COMPRAS";
CREATE GENERATOR "COMPROBANTES";
CREATE GENERATOR "DEPARTAMENTOS";
CREATE GENERATOR "DESCUENTOS";
CREATE GENERATOR "INVENTARIO";
CREATE GENERATOR "NOTASCREDITO";
CREATE GENERATOR "TIPOPAGO";
CREATE GENERATOR "USUARIOS";
CREATE GENERATOR "VENTAS";
CREATE GENERATOR "XCOBRAR";
CREATE GENERATOR "XPAGAR";


/* Triggers only will work for SQL triggers */

CREATE TRIGGER "INVENTARIO" FOR "INVENTARIO" 
ACTIVE BEFORE INSERT POSITION 0
as begin
    new.clave = gen_id(inventario,1);
end
 ;

CREATE TRIGGER "AREASVENTA" FOR "AREASVENTA" 
ACTIVE BEFORE INSERT POSITION 0
as begin
    new.clave = gen_id(areasventa,1);
end
 ;

CREATE TRIGGER "ARTICULOS" FOR "ARTICULOS" 
ACTIVE BEFORE INSERT POSITION 0
as begin
    new.clave = gen_id(articulos,1);
end
 ;

CREATE TRIGGER "CATEGORIAS" FOR "CATEGORIAS" 
ACTIVE BEFORE INSERT POSITION 0
as begin
    new.clave = gen_id(categorias,1);
end
 ;

CREATE TRIGGER "CLIENTES" FOR "CLIENTES" 
ACTIVE BEFORE INSERT POSITION 0
as begin
    new.clave = gen_id(clientes,1);
end
 ;

CREATE TRIGGER "COMPRAS" FOR "COMPRAS" 
ACTIVE BEFORE INSERT POSITION 0
as begin
    new.clave = gen_id(compras,1);
end
 ;

CREATE TRIGGER "COMPROBANTES" FOR "COMPROBANTES" 
ACTIVE BEFORE INSERT POSITION 0
as begin
    new.clave = gen_id(comprobantes,1);
end
 ;

CREATE TRIGGER "DEPARTAMENTOS" FOR "DEPARTAMENTOS" 
ACTIVE BEFORE INSERT POSITION 0
as begin
    new.clave = gen_id(departamentos,1);
end
 ;

CREATE TRIGGER "DESCUENTOS" FOR "DESCUENTOS" 
ACTIVE BEFORE INSERT POSITION 0
as begin
    new.clave = gen_id(descuentos,1);
end
 ;

CREATE TRIGGER "NOTASCREDITO" FOR "NOTASCREDITO" 
ACTIVE BEFORE INSERT POSITION 0
as begin
    new.clave = gen_id(notascredito,1);
end
 ;

CREATE TRIGGER "TIPOPAGO" FOR "TIPOPAGO" 
ACTIVE BEFORE INSERT POSITION 0
as begin
    new.clave = gen_id(tipopago,1);
end
 ;

CREATE TRIGGER "USUARIOS" FOR "USUARIOS" 
ACTIVE BEFORE INSERT POSITION 0
as begin
    new.clave = gen_id(usuarios,1);
end
 ;

CREATE TRIGGER "VENTAS" FOR "VENTAS" 
ACTIVE BEFORE INSERT POSITION 0
as begin
    new.clave = gen_id(ventas,1);
end
 ;

CREATE TRIGGER "COBRAR" FOR "XCOBRAR" 
ACTIVE BEFORE INSERT POSITION 0
as begin
    new.clave = gen_id(xcobrar,1);
end
 ;

CREATE TRIGGER "PAGAR" FOR "XPAGAR" 
ACTIVE BEFORE INSERT POSITION 0
as begin
    new.clave = gen_id(xpagar,1);
end
 ;

COMMIT WORK ;

/* Grant Roles for this database */


/* Grant permissions for this database */

